spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flyway
    username: root
    password:  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  flyway:
    check-location: false
   
server:
  port: 9001
  
jwt:
  secret: BIRLTROCAESSAPORR@
  expiration: 604800