spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flyway
    username: root
    password:  
  jpa:
    hibernate:
      ddl-auto: create

  flyway:
    check-location: false
   
server:
  port: 9001
  
jwt:
  secret: BIRLTROCAESSAPORR@
  expiration: 604800