spring:
  datasource:
    driver-class-name: com.cj.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flyway
    username: root
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create

  flyway:
    check-location: false
   
    